// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import * as core from "../../../../../../core/index.js";
import { mergeHeaders } from "../../../../../../core/headers.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as MyOrganization from "../../../../../index.js";
import { DomainsClient } from "../resources/domains/client/Client.js";
import { ProvisioningClient } from "../resources/provisioning/client/Client.js";

export declare namespace IdentityProvidersClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class IdentityProvidersClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<IdentityProvidersClient.Options>;
    protected _domains: DomainsClient | undefined;
    protected _provisioning: ProvisioningClient | undefined;

    constructor(options: IdentityProvidersClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get domains(): DomainsClient {
        return (this._domains ??= new DomainsClient(this._options));
    }

    public get provisioning(): ProvisioningClient {
        return (this._provisioning ??= new ProvisioningClient(this._options));
    }

    /**
     * List the identity providers associated with this organization.
     *
     * @param {IdentityProvidersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.identityProviders.list()
     */
    public list(
        requestOptions?: IdentityProvidersClient.RequestOptions,
    ): core.HttpResponsePromise<MyOrganization.ListIdentityProvidersResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(
        requestOptions?: IdentityProvidersClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyOrganization.ListIdentityProvidersResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["read:my_org:identity_providers"] },
                { OAuth2AuthCode: ["read:my_org:identity_providers"] },
            ],
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                "identity-providers",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyOrganization.ListIdentityProvidersResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/identity-providers");
    }

    /**
     * Create an identity provider associated with this organization.
     *
     * @param {MyOrganization.CreateIdentityProviderRequestContent} request
     * @param {IdentityProvidersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.ConflictError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.identityProviders.create({
     *         name: "oidcIdp",
     *         strategy: "oidc",
     *         domains: ["mydomain.com"],
     *         display_name: "OIDC IdP",
     *         show_as_button: true,
     *         assign_membership_on_login: false,
     *         is_enabled: true,
     *         options: {
     *             type: "front_channel",
     *             client_id: "a8f3b2e7-5d1c-4f9a-8b0d-2e1c3a5b6f7d",
     *             client_secret: "KzQp2sVxR8nTgMjFhYcEWuLoIbDvUoC6A9B1zX7yWqFjHkGrP5sQdLmNp",
     *             discovery_url: "https://{yourDomain}/.well-known/openid-configuration"
     *         }
     *     })
     */
    public create(
        request: MyOrganization.CreateIdentityProviderRequestContent,
        requestOptions?: IdentityProvidersClient.RequestOptions,
    ): core.HttpResponsePromise<MyOrganization.CreateIdentityProviderResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: MyOrganization.CreateIdentityProviderRequestContent,
        requestOptions?: IdentityProvidersClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyOrganization.CreateIdentityProviderResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["create:my_org:identity_providers"] },
                { OAuth2AuthCode: ["create:my_org:identity_providers"] },
            ],
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                "identity-providers",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyOrganization.CreateIdentityProviderResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyOrganization.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 409:
                    throw new MyOrganization.ConflictError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/identity-providers");
    }

    /**
     * Retrieve the details for one particular identity-provider.
     *
     * @param {MyOrganization.GetIdentityProvidersRequest} request
     * @param {IdentityProvidersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.identityProviders.get({
     *         idp_id: "idp_id"
     *     })
     */
    public get(
        request: MyOrganization.GetIdentityProvidersRequest,
        requestOptions?: IdentityProvidersClient.RequestOptions,
    ): core.HttpResponsePromise<MyOrganization.GetIdentityProviderResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: MyOrganization.GetIdentityProvidersRequest,
        requestOptions?: IdentityProvidersClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyOrganization.GetIdentityProviderResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["read:my_org:identity_providers"] },
                { OAuth2AuthCode: ["read:my_org:identity_providers"] },
            ],
        };
        const { idp_id: idpId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                `identity-providers/${core.url.encodePathParam(idpId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyOrganization.GetIdentityProviderResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyOrganization.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/identity-providers/{idp_id}");
    }

    /**
     * Delete an identity provider from this organization.
     *
     * @param {MyOrganization.DeleteIdentityProvidersRequest} request
     * @param {IdentityProvidersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.identityProviders.delete({
     *         idp_id: "idp_id"
     *     })
     */
    public delete(
        request: MyOrganization.DeleteIdentityProvidersRequest,
        requestOptions?: IdentityProvidersClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: MyOrganization.DeleteIdentityProvidersRequest,
        requestOptions?: IdentityProvidersClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["delete:my_org:identity_providers"] },
                { OAuth2AuthCode: ["delete:my_org:identity_providers"] },
            ],
        };
        const { idp_id: idpId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                `identity-providers/${core.url.encodePathParam(idpId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyOrganization.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/identity-providers/{idp_id}",
        );
    }

    /**
     * Update an identity provider associated with this organization.
     *
     * @param {MyOrganization.UpdateIdentityProvidersRequest} request
     * @param {IdentityProvidersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.identityProviders.update({
     *         idp_id: "idp_id",
     *         body: {
     *             display_name: "OIDC IdP",
     *             show_as_button: true,
     *             assign_membership_on_login: false,
     *             is_enabled: true,
     *             options: {
     *                 type: "front_channel",
     *                 client_id: "a8f3b2e7-5d1c-4f9a-8b0d-2e1c3a5b6f7d",
     *                 client_secret: "KzQp2sVxR8nTgMjFhYcEWuLoIbDvUoC6A9B1zX7yWqFjHkGrP5sQdLmNp",
     *                 discovery_url: "https://{yourDomain}/.well-known/openid-configuration"
     *             }
     *         }
     *     })
     */
    public update(
        request: MyOrganization.UpdateIdentityProvidersRequest,
        requestOptions?: IdentityProvidersClient.RequestOptions,
    ): core.HttpResponsePromise<MyOrganization.UpdateIdentityProviderResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: MyOrganization.UpdateIdentityProvidersRequest,
        requestOptions?: IdentityProvidersClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyOrganization.UpdateIdentityProviderResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["update:my_org:identity_providers"] },
                { OAuth2AuthCode: ["update:my_org:identity_providers"] },
            ],
        };
        const { idp_id: idpId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                `identity-providers/${core.url.encodePathParam(idpId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyOrganization.UpdateIdentityProviderResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyOrganization.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/identity-providers/{idp_id}",
        );
    }

    /**
     * Triggers a refresh of attribute mappings on the identity provider by overriding it with the admin defined defaults. The endpoint doesn't accept any body parameters.
     *
     * @param {MyOrganization.UpdateAttributesIdentityProvidersRequest} request
     * @param {IdentityProvidersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.identityProviders.updateAttributes({
     *         idp_id: "idp_id",
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    public updateAttributes(
        request: MyOrganization.UpdateAttributesIdentityProvidersRequest,
        requestOptions?: IdentityProvidersClient.RequestOptions,
    ): core.HttpResponsePromise<MyOrganization.GetIdentityProviderResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__updateAttributes(request, requestOptions));
    }

    private async __updateAttributes(
        request: MyOrganization.UpdateAttributesIdentityProvidersRequest,
        requestOptions?: IdentityProvidersClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyOrganization.GetIdentityProviderResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["update:my_org:identity_providers"] },
                { OAuth2AuthCode: ["update:my_org:identity_providers"] },
            ],
        };
        const { idp_id: idpId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                `identity-providers/${core.url.encodePathParam(idpId)}/update-attributes`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyOrganization.GetIdentityProviderResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyOrganization.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/identity-providers/{idp_id}/update-attributes",
        );
    }

    /**
     * Delete underlying identity provider from this organization.
     *
     * @param {MyOrganization.DetachIdentityProvidersRequest} request
     * @param {IdentityProvidersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.identityProviders.detach({
     *         idp_id: "idp_id"
     *     })
     */
    public detach(
        request: MyOrganization.DetachIdentityProvidersRequest,
        requestOptions?: IdentityProvidersClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__detach(request, requestOptions));
    }

    private async __detach(
        request: MyOrganization.DetachIdentityProvidersRequest,
        requestOptions?: IdentityProvidersClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["update:my_org:identity_providers_detach"] },
                { OAuth2AuthCode: ["update:my_org:identity_providers_detach"] },
            ],
        };
        const { idp_id: idpId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                `identity-providers/${core.url.encodePathParam(idpId)}/detach`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyOrganization.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/identity-providers/{idp_id}/detach",
        );
    }
}
