// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import { Configuration } from "../resources/configuration/client/Client.js";
import { Domains } from "../resources/domains/client/Client.js";
import { IdentityProviders } from "../resources/identityProviders/client/Client.js";
import { Members } from "../resources/members/client/Client.js";
import { Invitations } from "../resources/invitations/client/Client.js";

export declare namespace Organization {
    export interface Options extends BaseClientOptions {}
}

export class Organization {
    protected readonly _options: Organization.Options;
    protected _configuration: Configuration | undefined;
    protected _domains: Domains | undefined;
    protected _identityProviders: IdentityProviders | undefined;
    protected _members: Members | undefined;
    protected _invitations: Invitations | undefined;

    constructor(_options: Organization.Options) {
        this._options = _options;
    }

    public get configuration(): Configuration {
        return (this._configuration ??= new Configuration(this._options));
    }

    public get domains(): Domains {
        return (this._domains ??= new Domains(this._options));
    }

    public get identityProviders(): IdentityProviders {
        return (this._identityProviders ??= new IdentityProviders(this._options));
    }

    public get members(): Members {
        return (this._members ??= new Members(this._options));
    }

    public get invitations(): Invitations {
        return (this._invitations ??= new Invitations(this._options));
    }
}
