// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import * as core from "../../../../../../core/index.js";
import { mergeHeaders } from "../../../../../../core/headers.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as MyOrganization from "../../../../../index.js";
import { IdentityProvidersClient } from "../resources/identityProviders/client/Client.js";
import { VerifyClient } from "../resources/verify/client/Client.js";

export declare namespace DomainsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class DomainsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DomainsClient.Options>;
    protected _verify: VerifyClient | undefined;
    protected _identityProviders: IdentityProvidersClient | undefined;

    constructor(options: DomainsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get verify(): VerifyClient {
        return (this._verify ??= new VerifyClient(this._options));
    }

    public get identityProviders(): IdentityProvidersClient {
        return (this._identityProviders ??= new IdentityProvidersClient(this._options));
    }

    /**
     * Lists all domains pending and verified for an organization.
     *
     * @param {DomainsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.domains.list()
     */
    public list(
        requestOptions?: DomainsClient.RequestOptions,
    ): core.HttpResponsePromise<MyOrganization.ListOrganizationDomainsResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(
        requestOptions?: DomainsClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyOrganization.ListOrganizationDomainsResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["read:my_org:domains"] },
                { OAuth2AuthCode: ["read:my_org:domains"] },
            ],
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                "domains",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyOrganization.ListOrganizationDomainsResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/domains");
    }

    /**
     * Create a new domain for an organization.
     *
     * @param {MyOrganization.CreateOrganizationDomainRequestContent} request
     * @param {DomainsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.ConflictError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.domains.create({
     *         domain: "acme.com"
     *     })
     */
    public create(
        request: MyOrganization.CreateOrganizationDomainRequestContent,
        requestOptions?: DomainsClient.RequestOptions,
    ): core.HttpResponsePromise<MyOrganization.CreateOrganizationDomainResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: MyOrganization.CreateOrganizationDomainRequestContent,
        requestOptions?: DomainsClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyOrganization.CreateOrganizationDomainResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["create:my_org:domains"] },
                { OAuth2AuthCode: ["create:my_org:domains"] },
            ],
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                "domains",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyOrganization.CreateOrganizationDomainResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyOrganization.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 409:
                    throw new MyOrganization.ConflictError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/domains");
    }

    /**
     * Retrieve a domain for an organization.
     *
     * @param {MyOrganization.GetDomainsRequest} request
     * @param {DomainsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.domains.get({
     *         domain_id: "domain_id"
     *     })
     */
    public get(
        request: MyOrganization.GetDomainsRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): core.HttpResponsePromise<MyOrganization.GetOrganizationDomainResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: MyOrganization.GetDomainsRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyOrganization.GetOrganizationDomainResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["read:my_org:domains"] },
                { OAuth2AuthCode: ["read:my_org:domains"] },
            ],
        };
        const { domain_id: domainId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                `domains/${core.url.encodePathParam(domainId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyOrganization.GetOrganizationDomainResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyOrganization.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/domains/{domain_id}");
    }

    /**
     * Remove a domain from this organization.
     *
     * @param {MyOrganization.DeleteDomainsRequest} request
     * @param {DomainsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.domains.delete({
     *         domain_id: "domain_id"
     *     })
     */
    public delete(
        request: MyOrganization.DeleteDomainsRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: MyOrganization.DeleteDomainsRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["delete:my_org:domains"] },
                { OAuth2AuthCode: ["delete:my_org:domains"] },
            ],
        };
        const { domain_id: domainId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                `domains/${core.url.encodePathParam(domainId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyOrganization.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/domains/{domain_id}");
    }
}
