// This file was auto-generated by Fern from our API Definition.

export class Auth0MyOrgTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, Auth0MyOrgTimeoutError.prototype);
    }
}
