// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../BaseClient.js";
import * as environments from "../../../../../../../../environments.js";
import * as core from "../../../../../../../../core/index.js";
import * as MyOrganization from "../../../../../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../core/headers.js";
import * as errors from "../../../../../../../../errors/index.js";

export declare namespace IdentityProviders {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class IdentityProviders {
    protected readonly _options: IdentityProviders.Options;

    constructor(_options: IdentityProviders.Options) {
        this._options = _options;
    }

    /**
     * Retrieve the list of identity providers that have a specific organization domain alias.
     *
     * @param {MyOrganization.OrgDomainId} domainId
     * @param {IdentityProviders.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.domains.identityProviders.get("domain_id")
     */
    public get(
        domainId: MyOrganization.OrgDomainId,
        requestOptions?: IdentityProviders.RequestOptions,
    ): core.HttpResponsePromise<MyOrganization.ListDomainIdentityProvidersResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__get(domainId, requestOptions));
    }

    private async __get(
        domainId: MyOrganization.OrgDomainId,
        requestOptions?: IdentityProviders.RequestOptions,
    ): Promise<core.WithRawResponse<MyOrganization.ListDomainIdentityProvidersResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["read:my_org:domains", "read:my_org:identity_providers"] },
                { OAuth2AuthCode: ["read:my_org:domains", "read:my_org:identity_providers"] },
            ],
        };
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader(_metadata) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                `domains/${core.url.encodePathParam(domainId)}/identity-providers`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyOrganization.ListDomainIdentityProvidersResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyOrganization.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MyOrganizationError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MyOrganizationTimeoutError(
                    "Timeout exceeded when calling GET /domains/{domain_id}/identity-providers.",
                );
            case "unknown":
                throw new errors.MyOrganizationError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(endpointMetadata: core.EndpointMetadata): Promise<string> {
        return `Bearer ${await core.EndpointSupplier.get(this._options.token, { endpointMetadata })}`;
    }
}
