// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import * as core from "../../../../../../core/index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as MyOrganization from "../../../../../index.js";

export declare namespace InvitationsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class InvitationsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<InvitationsClient.Options>;

    constructor(options: InvitationsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Retrieve a list of all member invitations for this Organization.
     *
     * @param {MyOrganization.ListMemberInvitationsRequestParameters} request
     * @param {InvitationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.invitations.list({
     *         fields: "fields",
     *         include_fields: true,
     *         from: "from",
     *         take: 1,
     *         sort: "sort"
     *     })
     */
    public async list(
        request: MyOrganization.ListMemberInvitationsRequestParameters = {},
        requestOptions?: InvitationsClient.RequestOptions,
    ): Promise<core.Page<MyOrganization.MemberInvitation, MyOrganization.ListMembersInvitationsResponseContent>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: MyOrganization.ListMemberInvitationsRequestParameters,
            ): Promise<core.WithRawResponse<MyOrganization.ListMembersInvitationsResponseContent>> => {
                const _metadata: core.EndpointMetadata = {
                    security: [
                        { OAuth2ClientCredentials: ["read:my_org:member_invitations"] },
                        { OAuth2AuthCode: ["read:my_org:member_invitations"] },
                    ],
                };
                const {
                    fields,
                    include_fields: includeFields = true,
                    from: from_,
                    take = 50,
                    sort = "created_at:-1",
                } = request;
                const _queryParams: Record<string, unknown> = {
                    fields,
                    include_fields: includeFields,
                    from: from_,
                    take,
                    sort,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
                    endpointMetadata: _metadata,
                });
                let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.MyOrganizationEnvironment.Default,
                        "member-invitations",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    endpointMetadata: _metadata,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as MyOrganization.ListMembersInvitationsResponseContent,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new MyOrganization.BadRequestError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new MyOrganization.UnauthorizedError(
                                _response.error.body as MyOrganization.ErrorResponseContent,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new MyOrganization.ForbiddenError(
                                _response.error.body as MyOrganization.ErrorResponseContent,
                                _response.rawResponse,
                            );
                        case 404:
                            throw new MyOrganization.NotFoundError(
                                _response.error.body as MyOrganization.ErrorResponseContent,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new MyOrganization.TooManyRequestsError(
                                _response.error.body as MyOrganization.ErrorResponseContent,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.MyOrganizationError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/member-invitations");
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<MyOrganization.MemberInvitation, MyOrganization.ListMembersInvitationsResponseContent>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.next != null && !(typeof response?.next === "string" && response?.next === ""),
            getItems: (response) => response?.invitations ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "from", response?.next));
            },
        });
    }

    /**
     * Create one or more member invitations for this Organization. If an active invitation already exists for a user, generating a new invitation will automatically revoke any outstanding invitations for that user. Roles specified in the payload will be granted to the user upon acceptance of the invitation.
     *
     * @param {MyOrganization.CreateMemberInvitationRequestContent} request
     * @param {InvitationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.invitations.create({
     *         invitees: [{
     *                 email: "user@example.com",
     *                 roles: ["rol_0000000000000001"]
     *             }],
     *         inviter: {
     *             name: "Allison the Admin"
     *         },
     *         identity_provider_id: "con_2CZPv6IY0gWzDaQJ",
     *         ttl_sec: 3600
     *     })
     */
    public create(
        request: MyOrganization.CreateMemberInvitationRequestContent,
        requestOptions?: InvitationsClient.RequestOptions,
    ): core.HttpResponsePromise<MyOrganization.CreateMemberInvitationResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: MyOrganization.CreateMemberInvitationRequestContent,
        requestOptions?: InvitationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyOrganization.CreateMemberInvitationResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["create:my_org:member_invitations"] },
                { OAuth2AuthCode: ["create:my_org:member_invitations"] },
            ],
        };
        const { "auth0-custom-domain": auth0CustomDomain, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "auth0-custom-domain": auth0CustomDomain }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                "member-invitations",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyOrganization.CreateMemberInvitationResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyOrganization.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/member-invitations");
    }

    /**
     * Retrieve details of a member invitation specified by ID for this Organization.
     *
     * @param {MyOrganization.InvitationId} invitation_id
     * @param {MyOrganization.GetMemberInvitationRequestParameters} request
     * @param {InvitationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.invitations.get("invitation_id", {
     *         fields: "fields",
     *         include_fields: true
     *     })
     */
    public get(
        invitation_id: MyOrganization.InvitationId,
        request: MyOrganization.GetMemberInvitationRequestParameters = {},
        requestOptions?: InvitationsClient.RequestOptions,
    ): core.HttpResponsePromise<MyOrganization.GetMemberInvitationResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__get(invitation_id, request, requestOptions));
    }

    private async __get(
        invitation_id: MyOrganization.InvitationId,
        request: MyOrganization.GetMemberInvitationRequestParameters = {},
        requestOptions?: InvitationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<MyOrganization.GetMemberInvitationResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["read:my_org:member_invitations"] },
                { OAuth2AuthCode: ["read:my_org:member_invitations"] },
            ],
        };
        const { fields, include_fields: includeFields = true } = request;
        const _queryParams: Record<string, unknown> = {
            fields,
            include_fields: includeFields,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                `member-invitations/${core.url.encodePathParam(invitation_id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyOrganization.GetMemberInvitationResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyOrganization.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/member-invitations/{invitation_id}",
        );
    }

    /**
     * Revoke a member invitation specified by ID for this Organization.
     *
     * @param {MyOrganization.InvitationId} invitation_id
     * @param {InvitationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.invitations.delete("invitation_id")
     */
    public delete(
        invitation_id: MyOrganization.InvitationId,
        requestOptions?: InvitationsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(invitation_id, requestOptions));
    }

    private async __delete(
        invitation_id: MyOrganization.InvitationId,
        requestOptions?: InvitationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["delete:my_org:member_invitations"] },
                { OAuth2AuthCode: ["delete:my_org:member_invitations"] },
            ],
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                `member-invitations/${core.url.encodePathParam(invitation_id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyOrganization.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/member-invitations/{invitation_id}",
        );
    }
}
