// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

export interface AssignOrganizationMemberRoleResponseContent {
    roles?: Auth0MyOrg.OrgMemberRole[];
}
