// This file was auto-generated by Fern from our API Definition.

export interface BaseUserAttributeMapItem {
    /** The name of the user attribute. */
    user_attribute: string;
    /** The description of the user attribute. */
    description?: string | undefined;
    /** The label of the user attribute. */
    label?: string | undefined;
    /** Indicates if the attribute is required. */
    is_required: boolean;
    /** Indicates whether this attribute is not part of the admin defined schema but is provided by the source. The property will be removed when a refresh operation is performed. */
    is_extra: boolean;
    /** Indicates whether this attribute is expected but not provided by the admin defined schema. The property will   be added when a refresh operation is performed. */
    is_missing: boolean;
}
