// This file was auto-generated by Fern from our API Definition.

/** */
export const ConnectionProfileEnabledFeaturesEnum = {
    Scim: "scim",
    UniversalLogout: "universal_logout",
} as const;
export type ConnectionProfileEnabledFeaturesEnum =
    (typeof ConnectionProfileEnabledFeaturesEnum)[keyof typeof ConnectionProfileEnabledFeaturesEnum];
