// This file was auto-generated by Fern from our API Definition.

/** If set, this value will be set to any connection that is created using this Connection Profile. If not provided it’ll default to on_each_login. */
export const ConnectionProfileProvisioningOnLoginEnum = {
    NeverOnLogin: "never_on_login",
    OnFirstLogin: "on_first_login",
    OnEachLogin: "on_each_login",
} as const;
export type ConnectionProfileProvisioningOnLoginEnum =
    (typeof ConnectionProfileProvisioningOnLoginEnum)[keyof typeof ConnectionProfileProvisioningOnLoginEnum];
