// This file was auto-generated by Fern from our API Definition.

/** Defines the default and the maximum allowed scopes that can be requested for a SCIM token. */
export const ConnectionProfileProvisioningScimTokensEnum = {
    GetUsers: "get:users",
    PostUsers: "post:users",
    PatchUsers: "patch:users",
    DeleteUsers: "delete:users",
    PutUsers: "put:users",
} as const;
export type ConnectionProfileProvisioningScimTokensEnum =
    (typeof ConnectionProfileProvisioningScimTokensEnum)[keyof typeof ConnectionProfileProvisioningScimTokensEnum];
