// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

/**
 * The organization of the connection profile.
 */
export interface ConnectionProfileOrganization {
    show_as_button?: Auth0MyOrg.ConnectionProfileOrganizationShowAsButtonEnum;
    assign_membership_on_login?: Auth0MyOrg.ConnectionProfileOrganizationAssignMembershipEnum;
}
