// This file was auto-generated by Fern from our API Definition.

/** Sets the policy for domain verification requirements */
export const ConnectionProfileDomainVerificationEnum = {
    None: "none",
    Optional: "optional",
    Required: "required",
} as const;
export type ConnectionProfileDomainVerificationEnum =
    (typeof ConnectionProfileDomainVerificationEnum)[keyof typeof ConnectionProfileDomainVerificationEnum];
