// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

/**
 * Strategy-specific overrides for this attribute
 */
export interface ConnectionProfileStrategyOverride {
    adfs?: Auth0MyOrg.ConnectionProfileStrategyOverrideAdfs;
    googleapps?: Auth0MyOrg.ConnectionProfileStrategyOverrideGoogleApps;
    oidc?: Auth0MyOrg.ConnectionProfileStrategyOverrideOidc;
    okta?: Auth0MyOrg.ConnectionProfileStrategyOverrideOkta;
    pingfederate?: Auth0MyOrg.ConnectionProfileStrategyOverridePingFederate;
    samlp?: Auth0MyOrg.ConnectionProfileStrategyOverrideSamlp;
    waad?: Auth0MyOrg.ConnectionProfileStrategyOverrideWaad;
}
