// This file was auto-generated by Fern from our API Definition.

/** Indicates if membership should be assigned on login. */
export const ConnectionProfileOrganizationAssignMembershipEnum = {
    None: "none",
    Optional: "optional",
    Required: "required",
} as const;
export type ConnectionProfileOrganizationAssignMembershipEnum =
    (typeof ConnectionProfileOrganizationAssignMembershipEnum)[keyof typeof ConnectionProfileOrganizationAssignMembershipEnum];
