// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface CreateMemberInvitationInvitee {
    /** The invitee's email. */
    email: string;
    /** List of role IDs to associate with the user. */
    roles?: MyOrganization.RoleId[] | undefined;
}
