// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface CrossAppAccessResourceAppStatusConfig {
    /** The value applied to `cross_app_access_resource_app.status` when an identity provider is created and no other value is specified. */
    default_value: MyOrganization.CrossAppAccessResourceAppStatusConfigEnum;
    /** A list of values, other than `default_value`, that may be set for `cross_app_access_resource_app.status` when creating or updating an identity provider. If omitted, only `default_value` is permitted. */
    allowed_values?: MyOrganization.CrossAppAccessResourceAppStatusConfigEnum[] | undefined;
}
