// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

/**
 * Defines the allowed behavior of the `cross_app_access_resource_app` field on identity providers.
 */
export interface CrossAppAccessResourceAppConfig {
    status: MyOrganization.CrossAppAccessResourceAppStatusConfig;
}
