// This file was auto-generated by Fern from our API Definition.

/** Allowed status values for the cross-app access resource application. */
export const CrossAppAccessResourceAppStatusConfigEnum = {
    Enabled: "enabled",
    Disabled: "disabled",
} as const;
export type CrossAppAccessResourceAppStatusConfigEnum =
    (typeof CrossAppAccessResourceAppStatusConfigEnum)[keyof typeof CrossAppAccessResourceAppStatusConfigEnum];
