// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface DomainIdp {
    id: MyOrganization.IdpId;
    /** The name of the identity provider */
    name: string;
    /** Identity provider name used on the login screen. */
    display_name?: string;
}
