// This file was auto-generated by Fern from our API Definition.

/** Sets the policy for domain verification requirements */
export const DomainVerificationEnum = {
    None: "none",
    Optional: "optional",
    Required: "required",
} as const;
export type DomainVerificationEnum = (typeof DomainVerificationEnum)[keyof typeof DomainVerificationEnum];
