// This file was auto-generated by Fern from our API Definition.

export interface ErrorResponseContent {
    /** A URI that describes the error. */
    type: string;
    /** The HTTP status code result of the request. */
    status: number;
    /** A brief description of the error. */
    title: string;
    /** A detailed description of the error. */
    detail: string;
}
