// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

export interface GetConfigurationResponseContent {
    /** Array of supported strategies */
    allowed_strategies?: Auth0MyOrg.IdpStrategyEnum[];
    connection_deletion_behavior?: Auth0MyOrg.IdpConnectionDeletionBehaviorEnum;
}
