// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface GetIdPProvisioningConfigResponseContent extends MyOrganization.IdpProvisioningConfigRead {
    created_at?: string | undefined;
    updated_on?: string | undefined;
}
