// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface GetIdPProvisioningConfigResponseContent extends MyOrganization.IdpProvisioningConfig {
    created_at?: string;
    updated_on?: string;
}
