// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

export interface GetIdPProvisioningConfigResponseContent extends Auth0MyOrg.IdpProvisioningConfig {
    created_at?: string;
    updated_on?: string;
}
