// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

/**
 * The provisioning configuration supported by the identity provider
 */
export interface IdentityProvidersConfigProvisioningConfiguration {
    on_login?: MyOrganization.IdentityProvidersConfigProvisioningConfigurationOnLogin | undefined;
    scim?: (MyOrganization.IdentityProvidersConfigProvisioningConfigurationScim | null) | undefined;
}
