// This file was auto-generated by Fern from our API Definition.

/** The enabled features for the identity provider */
export const IdentityProvidersConfigEnabledFeaturesEnum = {
    Provisioning: "provisioning",
    Logout: "logout",
} as const;
export type IdentityProvidersConfigEnabledFeaturesEnum =
    (typeof IdentityProvidersConfigEnabledFeaturesEnum)[keyof typeof IdentityProvidersConfigEnabledFeaturesEnum];
