// This file was auto-generated by Fern from our API Definition.

/**
 * The organization config for identity providers.
 */
export interface IdentityProvidersConfigOrganization {
    /** If Org Admin can set show_as_button */
    can_set_show_as_button: boolean;
    /** If Org Admin can set assign_membership_on_login */
    can_set_assign_membership_on_login: boolean;
}
