// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

/**
 * It is an object which contains domain verification related rules and restrictions.
 */
export interface IdentityProvidersConfigDomainAlias {
    domain_verification: MyOrganization.DomainVerificationEnum;
}
