// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface IdentityProvidersConfig {
    organization: MyOrganization.IdentityProvidersConfigOrganization;
    strategies: MyOrganization.IdentityProvidersConfigStrategyOverride;
    domain_aliases_config: MyOrganization.IdentityProvidersConfigDomainAlias;
}
