// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

/**
 * Provisioning configuration for SCIM
 */
export interface IdentityProvidersConfigProvisioningConfigurationScim {
    tokens: MyOrganization.IdentityProvidersConfigProvisioningConfigurationScimTokens;
}
