// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

/**
 * Identity providers strategy configs
 */
export interface IdentityProvidersConfigStrategyBase {
    /** Enabled features for a connections profile strategy override. */
    enabled_features: MyOrganization.IdentityProvidersConfigEnabledFeaturesEnum[];
    provisioning_methods: MyOrganization.IdentityProvidersConfigProvisioningMethodsEnum[];
}
