// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

/**
 * Strategy-specific overrides for identity providers
 */
export interface IdentityProvidersConfigStrategyOverride {
    adfs?: MyOrganization.IdentityProviderConfigAdfs;
    googleapps?: MyOrganization.IdentityProviderConfigGoogleApps;
    oidc?: MyOrganization.IdentityProviderConfigOidc;
    okta?: MyOrganization.IdentityProviderConfigOkta;
    pingfederate?: MyOrganization.IdentityProviderConfigPingFederate;
    samlp?: MyOrganization.IdentityProviderConfigSamlp;
    waad?: MyOrganization.IdentityProviderConfigWaad;
}
