// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface IdentityProvidersConfigProvisioningConfigurationScimTokens {
    scopes?: MyOrganization.IdentityProvidersConfigProvisioningConfigurationScimTokensScopes | undefined;
    default_expiry?: (number | null) | undefined;
    max_allowed_expiry?: (number | null) | undefined;
}
