// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

/**
 * Strategy-specific overrides for identity providers
 */
export interface IdentityProvidersConfigStrategyOverride {
    adfs?: MyOrganization.IdentityProviderConfigAdfs | undefined;
    "google-apps"?: MyOrganization.IdentityProviderConfigGoogleApps | undefined;
    oidc?: MyOrganization.IdentityProviderConfigOidc | undefined;
    okta?: MyOrganization.IdentityProviderConfigOkta | undefined;
    pingfederate?: MyOrganization.IdentityProviderConfigPingFederate | undefined;
    samlp?: MyOrganization.IdentityProviderConfigSamlp | undefined;
    waad?: MyOrganization.IdentityProviderConfigWaad | undefined;
}
