// This file was auto-generated by Fern from our API Definition.

/** Specifies whether deletion of a connection is always allowed, or only when the connection has no associated users */
export const IdpConnectionDeletionBehaviorEnum = {
    Allow: "allow",
    AllowIfEmpty: "allow_if_empty",
} as const;
export type IdpConnectionDeletionBehaviorEnum =
    (typeof IdpConnectionDeletionBehaviorEnum)[keyof typeof IdpConnectionDeletionBehaviorEnum];
