// This file was auto-generated by Fern from our API Definition.

export interface IdpGoogleAppsOptionsResponse {
    /** Google Workspace domain name for your organization. */
    domain?: string;
    /** Unique identifier for your registered Google application. */
    client_id?: string;
    /** A URL pointing to an image file that represents your client application. */
    icon_url?: string;
}
