// This file was auto-generated by Fern from our API Definition.

export interface IdpOktaOptionsRequest {
    /** Okta's domain name for your organization. */
    domain: string;
    /** Unique identifier for your registered Okta application */
    client_id: string;
    /** String used to gain access to your registered Okta application. */
    client_secret: string;
    /** A URL pointing to an image file that represents your client application. */
    icon_url?: string;
}
