// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

/**
 * Identity provider specific options.  Requires access_level to be 'full'.
 */
export interface IdpOidcUpdateRequest extends MyOrganization.IdpUpdateBase {
    /** Identity provider specific options.  Requires access_level to be 'full'. */
    options?: MyOrganization.IdpOidcOptionsRequest;
}
