// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

/**
 * Identity provider specific options.
 */
export interface IdpPingFederate {
    strategy: "pingfederate";
    /** Identity provider specific options. */
    options: Auth0MyOrg.IdpPingFederateOptions;
    id?: Auth0MyOrg.IdpId;
    /** The name of the identity provider */
    name: string;
    /** List of domains for Home Realm Discovery (HRD) */
    domains?: string[];
    /** Identity provider name used on the login screen. */
    display_name?: string;
    /** Enables showing a button for the connection in the login page (new experience only). If false, it will be usable only by Home Realm Discovery (HRD). */
    show_as_button?: boolean;
    /** If true, the user will be made a member of the organization upon login. */
    assign_membership_on_login?: boolean;
    /** True if the identity provider is enabled for the organization. */
    is_enabled?: boolean;
    access_level?: Auth0MyOrg.OrganizationAccessLevelEnum;
}
