// This file was auto-generated by Fern from our API Definition.

export interface IdpProvisioningFieldMapItem {
    provisioning_field: string;
    user_attribute: string;
    description: string;
    label: string;
}
