// This file was auto-generated by Fern from our API Definition.

/** HTTP binding supported by the IdP. */
export const IdpProtocolBindingTypeEnum = {
    UrnOasisNamesTcSaml20BindingsHttpRedirect: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
    UrnOasisNamesTcSaml20BindingsHttpPost: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
} as const;
export type IdpProtocolBindingTypeEnum = (typeof IdpProtocolBindingTypeEnum)[keyof typeof IdpProtocolBindingTypeEnum];
