// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

export interface IdpPingFederateOptions {
    /** Algorithm Auth0 will use to sign the SAML assertions. Ensure this matches your PingFederate Server's configuration. */
    signatureAlgorithm?: string;
    /** Algorithm Auth0 will use for the sign request digest. Ensure this matches your PingFederate Server's configuration. */
    digestAlgorithm?: string;
    /** Indicates whether PingFederate should digitally sign outgoing SAML authentication requests to relying parties */
    signSAMLRequest?: boolean;
    /** URL provided by PingFederate which returns information used for creating the connection */
    metadataUrl?: string;
    /** A value derived from decoding the signingCert. This should not be updated directly, instead update the signingCertificate to decode a new value for this field */
    cert?: string;
    /** PingFederate Server public key (encoded in PEM or CER) you retrieved from the IdP */
    signingCert?: string;
    idpInitiated?: Auth0MyOrg.IdpOptionsIdpInitiated;
    /** A URL pointing to an image file that represents your client application. */
    icon_url?: string;
}
