// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface IdpPingFederateOptionsResponse {
    signatureAlgorithm?: MyOrganization.IdpSignAlgTypeEnum;
    digestAlgorithm?: MyOrganization.IdpSignAlgDigestTypeEnum;
    /** Indicates whether PingFederate should digitally sign outgoing SAML authentication requests to relying parties */
    signSAMLRequest?: boolean;
    /** URL provided by PingFederate which returns information used for creating the connection */
    pingFederateBaseUrl?: string;
    /** A value derived from decoding the signingCert. This should not be updated directly, instead update the signingCertificate to decode a new value for this field */
    cert?: string;
    idpInitiated?: MyOrganization.IdpOptionsIdpInitiated;
    /** A URL pointing to an image file that represents your client application. */
    icon_url?: string;
}
