// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

/**
 * Identity provider specific options.  Requires access_level to be 'full'.
 */
export interface IdpPingFederateUpdate extends Auth0MyOrg.IdpUpdateBase {
    /** Identity provider specific options.  Requires access_level to be 'full'. */
    options?: Auth0MyOrg.IdpPingFederateOptions;
}
