// This file was auto-generated by Fern from our API Definition.

/** The type of the identity provider */
export const IdpStrategyEnum = {
    Adfs: "adfs",
    GoogleApps: "google-apps",
    Oidc: "oidc",
    Okta: "okta",
    Pingfederate: "pingfederate",
    Samlp: "samlp",
    Waad: "waad",
} as const;
export type IdpStrategyEnum = (typeof IdpStrategyEnum)[keyof typeof IdpStrategyEnum];
