// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export type IdpSamlpOptionsRequest =
    | {
          metadataUrl: string;
          signSAMLRequest: boolean;
          signatureAlgorithm?: MyOrganization.IdpSignAlgTypeEnum | undefined;
          digestAlgorithm?: MyOrganization.IdpSignAlgDigestTypeEnum | undefined;
          protocolBinding?: MyOrganization.IdpProtocolBindingTypeEnum | undefined;
          bindingMethod?: string | undefined;
          cert?: string | undefined;
          idpInitiated?: MyOrganization.IdpOptionsIdpInitiated | undefined;
          icon_url?: string | undefined;
      }
    | {
          signInEndpoint: string;
          cert: string;
          signSAMLRequest: boolean;
          signatureAlgorithm?: MyOrganization.IdpSignAlgTypeEnum | undefined;
          digestAlgorithm?: MyOrganization.IdpSignAlgDigestTypeEnum | undefined;
          protocolBinding?: MyOrganization.IdpProtocolBindingTypeEnum | undefined;
          bindingMethod?: string | undefined;
          idpInitiated?: MyOrganization.IdpOptionsIdpInitiated | undefined;
          icon_url?: string | undefined;
      };
