// This file was auto-generated by Fern from our API Definition.

/** Select the algorithm digest used for signing */
export const IdpSignAlgDigestTypeEnum = {
    Sha256: "sha256",
    Sha1: "sha1",
} as const;
export type IdpSignAlgDigestTypeEnum = (typeof IdpSignAlgDigestTypeEnum)[keyof typeof IdpSignAlgDigestTypeEnum];
