// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface IdpScimTokenCreate extends MyOrganization.IdpScimTokenBase {
    /** The SCIM client's token. */
    token?: string;
}
