// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface IdpUserAttributeMapItem extends MyOrganization.BaseUserAttributeMapItem {
    /** The name(s) of the sso field. */
    sso_field: string[];
}
