// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export type IdpUpdateKnownRequest =
    | MyOrganization.IdpAdfsUpdateRequest
    | MyOrganization.IdpGoogleAppsUpdateRequest
    | MyOrganization.IdpOidcUpdateRequest
    | MyOrganization.IdpOktaUpdateRequest
    | MyOrganization.IdpPingFederateUpdateRequest
    | MyOrganization.IdpSamlpUpdateRequest
    | MyOrganization.IdpWaadUpdateRequest;
