// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

export type IdpUpdateKnown =
    | Auth0MyOrg.IdpAdfsUpdate
    | Auth0MyOrg.IdpGoogleAppsUpdate
    | Auth0MyOrg.IdpOidcUpdate
    | Auth0MyOrg.IdpOktaUpdate
    | Auth0MyOrg.IdpPingFederateUpdate
    | Auth0MyOrg.IdpSamlpUpdate
    | Auth0MyOrg.IdpWaadUpdate;
