// This file was auto-generated by Fern from our API Definition.

export interface IdpWaadOptions {
    /** Your Azure AD domain name. You can find this on your Azure AD directory's overview page in the Microsoft Azure portal. */
    domain?: string;
    /** Unique identifier for your registered Azure AD application. */
    client_id?: string;
    /** String used to gain access to your registered Azure AD application. */
    client_secret?: string;
    /** A URL pointing to an image file that represents your client application. */
    icon_url?: string;
}
