// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface ListOrganizationDomainsResponseContent {
    /** Pagination cursor for the next page of results */
    next?: string;
    organization_domains: MyOrganization.OrgDomain[];
}
