// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface ListMembersInvitationsResponseContent {
    /** Pagination cursor for the next page of results. */
    next?: string | undefined;
    /** Best-effort count of pending invitations in the result set (reflecting any active filters). Only present when include_totals=true. Capped at 1000. */
    total?: number | undefined;
    /** Whether counting stopped before reaching the true size of the result set. When true, 'total' is a lower bound (the true size is 'total' or greater); when false, 'total' reflects the full result set as counted. Only present when 'total' is present. */
    total_is_capped?: boolean | undefined;
    invitations?: MyOrganization.MemberInvitation[] | undefined;
}
