// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface ListRolesResponseContent {
    roles: MyOrganization.Role[];
    /** Pagination cursor for the next page of results */
    next?: string | undefined;
}
