// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

export interface ListOrganizationDomainsResponseContent {
    /** Pagination cursor for the next page of results */
    next?: string;
    organization_domains: Auth0MyOrg.OrgDomain[];
}
