// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface ListDomainIdentityProvidersResponseContent {
    identity_providers?: MyOrganization.DomainIdp[];
}
