// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

export interface ListIdpProvisioningScimTokensResponseContent {
    scim_tokens?: Auth0MyOrg.IdpScimTokenRead[];
}
