// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

export interface MemberInvitation {
    id: Auth0MyOrg.InvitationId;
    organization_id: Auth0MyOrg.OrgId;
    inviter: MemberInvitation.Inviter;
    invitee: MemberInvitation.Invitee;
    /** The Organizations client identifier. */
    client_id: string;
    connection_id: Auth0MyOrg.IdpId;
    /** The member invitation's created at timestamp. */
    created_at: string;
    /** The member invitation's expiry timestamp. */
    expires_at: string;
    roles: string[];
    /** The invitation URL for the member invitation. */
    invitation_url: string;
    /** The Ticket Identifier for the Member Invitation. */
    ticket_id: string;
}

export namespace MemberInvitation {
    export interface Inviter {
        /** The inviters name. */
        name?: string;
    }

    export interface Invitee {
        /** The email of the person receiving the invite. */
        email?: string;
    }
}
