// This file was auto-generated by Fern from our API Definition.

export const OauthScope = {
    /**
     * Read Organization Config */
    ReadMyOrgConfiguration: "read:my_org:configuration",
    /**
     * Read Organization Details */
    ReadMyOrgDetails: "read:my_org:details",
    /**
     * Update Organization Details */
    UpdateMyOrgDetails: "update:my_org:details",
    /**
     * Read Identity Providers for Organization */
    ReadMyOrgIdentityProviders: "read:my_org:identity_providers",
    /**
     * Create Identity Provider for Organization */
    CreateMyOrgIdentityProviders: "create:my_org:identity_providers",
    /**
     * Update Identity Provider for Organization */
    UpdateMyOrgIdentityProviders: "update:my_org:identity_providers",
    /**
     * Delete Identity Provider for Organization */
    DeleteMyOrgIdentityProviders: "delete:my_org:identity_providers",
    /**
     * Detach Identity Provider from Organization */
    UpdateMyOrgIdentityProvidersDetach: "update:my_org:identity_providers_detach",
    /**
     * Read Identity Provider Domain for Organization */
    ReadMyOrgIdentityProviderDomains: "read:my_org:identity_provider_domains",
    /**
     * Add Identity Provider Domain for Organization */
    CreateMyOrgIdentityProviderDomains: "create:my_org:identity_provider_domains",
    /**
     * Delete Identity Provider Domain for Organization */
    DeleteMyOrgIdentityProviderDomains: "delete:my_org:identity_provider_domains",
    /**
     * Create Domain for Organization */
    CreateMyOrgDomains: "create:my_org:domains",
    /**
     * Read Domains for Organization */
    ReadMyOrgDomains: "read:my_org:domains",
    /**
     * Update Domain for Organization */
    UpdateMyOrgDomains: "update:my_org:domains",
    /**
     * Delete Domain for Organization */
    DeleteMyOrgDomains: "delete:my_org:domains",
    /**
     * Read Identity Providers for Organization Domain */
    ReadMyOrgIdentityProvidersDomains: "read:my_org:identity_providers_domains",
    /**
     * Create Provisioning Config for Identity Provider */
    CreateMyOrgIdentityProviderProvisioning: "create:my_org:identity_provider_provisioning",
    /**
     * Read SCIM Provisioning for Identity Provider */
    ReadMyOrgIdentityProviderProvisioning: "read:my_org:identity_provider_provisioning",
    /**
     * Delete Provisioning Config for Identity Provider */
    DeleteMyOrgIdentityProviderProvisioning: "delete:my_org:identity_provider_provisioning",
    /**
     * Create SCIM Token for Identity Provider */
    CreateMyOrgScimTokens: "create:my_org:scim_tokens",
    /**
     * Read SCIM Token for Identity Provider */
    ReadMyOrgScimTokens: "read:my_org:scim_tokens",
    /**
     * Delete SCIM Token for Identity Provider */
    DeleteMyOrgScimTokens: "delete:my_org:scim_tokens",
    /**
     * Read Member Invitations for an Organization */
    ReadMyOrgMemberInvitations: "read:my_org:member_invitations",
    /**
     * Create a Member Invitation for an Organization */
    CreateMyOrgMemberInvitations: "create:my_org:member_invitations",
    /**
     * Delete Member Invitations for an Organization */
    DeleteMyOrgMemberInvitations: "delete:my_org:member_invitations",
    /**
     * Read Members for Organization */
    ReadMyOrgMembers: "read:my_org:members",
    /**
     * Delete Members for Organization */
    DeleteMyOrgMembers: "delete:my_org:members",
    /**
     * Read Roles for Members in Organization */
    ReadMyOrgMemberRoles: "read:my_org:member_roles",
    /**
     * Create Roles for Members in Organization */
    CreateMyOrgMemberRoles: "create:my_org:member_roles",
    /**
     * Update Roles for Members in Organization */
    UpdateMyOrgMemberRoles: "update:my_org:member_roles",
    /**
     * Delete Roles from Members for Organization */
    DeleteMyOrgMemberRoles: "delete:my_org:member_roles",
} as const;
export type OauthScope = (typeof OauthScope)[keyof typeof OauthScope];
