// This file was auto-generated by Fern from our API Definition.

/** */
export const OrganizationAccessLevelEnum = {
    None: "none",
    Readonly: "readonly",
    Limited: "limited",
    Full: "full",
} as const;
export type OrganizationAccessLevelEnum =
    (typeof OrganizationAccessLevelEnum)[keyof typeof OrganizationAccessLevelEnum];
