// This file was auto-generated by Fern from our API Definition.

/** The Organization Member Access Level: what an Organization Administrator can do to members authenticated via this connection. */
export const OrganizationMemberAccessLevelEnum = {
    None: "none",
    Readonly: "readonly",
    Limited: "limited",
    Full: "full",
} as const;
export type OrganizationMemberAccessLevelEnum =
    (typeof OrganizationMemberAccessLevelEnum)[keyof typeof OrganizationMemberAccessLevelEnum];
