// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

/**
 * Theme defines how to style the login pages.
 */
export interface OrgBranding {
    /** URL of logo to display on login page. */
    logo_url?: string | null;
    colors?: MyOrganization.OrgBrandingColors;
}
