// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface OrgDetails {
    id?: MyOrganization.OrgId;
    /** The name of this organization. */
    name?: string;
    /** Friendly name of this organization. */
    display_name?: string;
    branding?: MyOrganization.OrgBranding;
}
