// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

export interface OrgDetails {
    id?: Auth0MyOrg.OrgId;
    /** The name of this organization. */
    name?: string;
    /** Friendly name of this organization. */
    display_name?: string;
    /** Theme defines how to style the login pages. */
    branding?: OrgDetails.Branding;
}

export namespace OrgDetails {
    /**
     * Theme defines how to style the login pages.
     */
    export interface Branding {
        /** URL of logo to display on login page. */
        logo_url?: string | null;
        /** Color scheme used to customize the login pages. */
        colors?: Branding.Colors;
    }

    export namespace Branding {
        /**
         * Color scheme used to customize the login pages.
         */
        export interface Colors {
            /** HEX Color for primary elements. */
            primary: string;
            /** HEX Color for background. */
            page_background: string;
        }
    }
}
