// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

export interface OrgDomain {
    id: Auth0MyOrg.OrgDomainId;
    org_id: Auth0MyOrg.OrgId;
    domain: Auth0MyOrg.OrgDomainName;
    status: Auth0MyOrg.OrgDomainStatusEnum;
    /** Value used to verify the domain. */
    verification_txt: string;
    /** Stores the full domain where the TXT record should be added. */
    verification_host: string;
}
