// This file was auto-generated by Fern from our API Definition.

import * as Auth0MyOrg from "../index.js";

export interface OrgMember extends Auth0MyOrg.UserAttributes {
    user_id?: Auth0MyOrg.OrgMemberId;
    /** Is member a guest. */
    is_guest?: boolean;
    roles?: Auth0MyOrg.OrgMemberRole[];
    /** Date and time when this user was created (ISO_8601 format). */
    created_at?: string;
    /** Date and time when this user was last updated (ISO_8601 format). */
    updated_at?: string;
    /** Last date and time this user logged in (ISO_8601 format). */
    last_login?: string;
}
