// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface OrgMemberRole {
    id: MyOrganization.OrgMemberRoleId;
    name: string;
    description?: string;
}
