// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

/**
 * Configuration for third-party client access
 */
export interface OrgThirdPartyClientAccessConfig {
    default_value: MyOrganization.OrgThirdPartyClientAccessEnum;
    /** Allowed third-party client access values */
    allowed_values: MyOrganization.OrgThirdPartyClientAccessEnum[];
}
