// This file was auto-generated by Fern from our API Definition.

/** A valid third-party client access value */
export const OrgThirdPartyClientAccessEnum = {
    Allow: "allow",
    Block: "block",
} as const;
export type OrgThirdPartyClientAccessEnum =
    (typeof OrgThirdPartyClientAccessEnum)[keyof typeof OrgThirdPartyClientAccessEnum];
