// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

export interface UserStore {
    /** User store Id */
    id?: string | undefined;
    /** User store name */
    name?: string | undefined;
    /** User store display name */
    display_name?: string | undefined;
    access_level?: MyOrganization.OrganizationAccessLevelEnum | undefined;
    /** The Organization Member Access Level for this user store: what the Organization Admin can do to members authenticated via this connection. */
    member_access_level?: MyOrganization.OrganizationMemberAccessLevelEnum | undefined;
    /** Is the user store enabled */
    is_enabled?: boolean | undefined;
}
