// This file was auto-generated by Fern from our API Definition.

export interface UserAttributes {
    /** Email */
    email?: string | undefined;
    /** Full Name */
    name?: string | undefined;
    /** User nickname */
    nickname?: string | undefined;
    /** First name */
    given_name?: string | undefined;
    /** Last name */
    family_name?: string | undefined;
}
