// This file was auto-generated by Fern from our API Definition.

export interface ValidationErrorDetail {
    /** A detailed description of the error. */
    detail: string;
    /** The name of the invalid parameter. */
    field?: string;
    /** JSON Pointer that points to the exact location of the error in a JSON document being validated. */
    pointer?: string;
    /** Specifies the source of the error (e.g., body, query, or header in an HTML message). */
    source?: string;
}
