// This file was auto-generated by Fern from our API Definition.

/**
 * Rate limit information for write operations
 */
export interface XAuth0RateLimitWrite {
    limit_category: "global_limit_per_second_write";
    friendly_name: "My Org API  Rate Limit  Write";
    limit_type: "per_tenant";
}
