// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../BaseClient.js";
import * as environments from "../../../../../../../../environments.js";
import * as core from "../../../../../../../../core/index.js";
import * as MyOrganization from "../../../../../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../core/headers.js";
import * as errors from "../../../../../../../../errors/index.js";

export declare namespace IdentityProviders {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class IdentityProviders {
    protected readonly _options: IdentityProviders.Options;

    constructor(_options: IdentityProviders.Options) {
        this._options = _options;
    }

    /**
     * Retrieve the connection profile for the application. This will give the components all of the information they will need to be successful. The SDK provider for the components should manage fetching and caching this information for all components.
     *
     * @param {IdentityProviders.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.configuration.identityProviders.get()
     */
    public get(
        requestOptions?: IdentityProviders.RequestOptions,
    ): core.HttpResponsePromise<MyOrganization.GetIdpConfigurationResponseContent> {
        return core.HttpResponsePromise.fromPromise(this.__get(requestOptions));
    }

    private async __get(
        requestOptions?: IdentityProviders.RequestOptions,
    ): Promise<core.WithRawResponse<MyOrganization.GetIdpConfigurationResponseContent>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["read:my_org:configuration"] },
                { OAuth2AuthCode: ["read:my_org:configuration"] },
            ],
        };
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader(_metadata) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                "config/identity-providers",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
        });
        if (_response.ok) {
            return {
                data: _response.body as MyOrganization.GetIdpConfigurationResponseContent,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.MyOrganizationError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.MyOrganizationTimeoutError(
                    "Timeout exceeded when calling GET /config/identity-providers.",
                );
            case "unknown":
                throw new errors.MyOrganizationError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(endpointMetadata: core.EndpointMetadata): Promise<string> {
        return `Bearer ${await core.EndpointSupplier.get(this._options.token, { endpointMetadata })}`;
    }
}
