// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import * as core from "../../../../../../core/index.js";
import { mergeHeaders } from "../../../../../../core/headers.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as MyOrganization from "../../../../../index.js";

export declare namespace MembershipsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class MembershipsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<MembershipsClient.Options>;

    constructor(options: MembershipsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Remove one member from this Organization. The underlying user account is not deleted.
     *
     * @param {MyOrganization.DeleteOrganizationMembershipsRequestParameters} request
     * @param {MembershipsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link MyOrganization.BadRequestError}
     * @throws {@link MyOrganization.UnauthorizedError}
     * @throws {@link MyOrganization.ForbiddenError}
     * @throws {@link MyOrganization.NotFoundError}
     * @throws {@link MyOrganization.TooManyRequestsError}
     *
     * @example
     *     await client.organization.memberships.deleteMemberships({
     *         members: ["auth0|1234567890"]
     *     })
     */
    public deleteMemberships(
        request: MyOrganization.DeleteOrganizationMembershipsRequestParameters,
        requestOptions?: MembershipsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteMemberships(request, requestOptions));
    }

    private async __deleteMemberships(
        request: MyOrganization.DeleteOrganizationMembershipsRequestParameters,
        requestOptions?: MembershipsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _metadata: core.EndpointMetadata = {
            security: [
                { OAuth2ClientCredentials: ["delete:my_org:memberships"] },
                { OAuth2AuthCode: ["delete:my_org:memberships"] },
            ],
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest({
            endpointMetadata: _metadata,
        });
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.MyOrganizationEnvironment.Default,
                "delete-memberships",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            endpointMetadata: _metadata,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new MyOrganization.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new MyOrganization.UnauthorizedError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 403:
                    throw new MyOrganization.ForbiddenError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 404:
                    throw new MyOrganization.NotFoundError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                case 429:
                    throw new MyOrganization.TooManyRequestsError(
                        _response.error.body as MyOrganization.ErrorResponseContent,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.MyOrganizationError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/delete-memberships");
    }
}
