// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../../../mock-server/MockServerPool";
import { MyOrganizationClient } from "../../../../src/Client";
import * as MyOrganization from "../../../../src/api/index";

describe("IdentityProviders", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            organization: { can_set_show_as_button: true, can_set_assign_membership_on_login: false },
            strategies: {
                adfs: { enabled_features: ["provisioning"], provisioning_methods: ["scim"] },
                googleapps: { enabled_features: ["provisioning"], provisioning_methods: ["scim"] },
                oidc: { enabled_features: ["provisioning"], provisioning_methods: ["scim"] },
                okta: { enabled_features: ["provisioning"], provisioning_methods: ["scim"] },
                pingfederate: { enabled_features: ["provisioning"], provisioning_methods: ["scim"] },
                samlp: { enabled_features: ["provisioning", "logout"], provisioning_methods: ["scim"] },
                waad: { enabled_features: ["provisioning"], provisioning_methods: ["scim"] },
            },
            domain_aliases_config: { domain_verification: "none" },
        };
        server
            .mockEndpoint()
            .get("/config/identity-providers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organization.configuration.identityProviders.get();
        expect(response).toEqual({
            organization: {
                can_set_show_as_button: true,
                can_set_assign_membership_on_login: false,
            },
            strategies: {
                adfs: {
                    enabled_features: ["provisioning"],
                    provisioning_methods: ["scim"],
                },
                googleapps: {
                    enabled_features: ["provisioning"],
                    provisioning_methods: ["scim"],
                },
                oidc: {
                    enabled_features: ["provisioning"],
                    provisioning_methods: ["scim"],
                },
                okta: {
                    enabled_features: ["provisioning"],
                    provisioning_methods: ["scim"],
                },
                pingfederate: {
                    enabled_features: ["provisioning"],
                    provisioning_methods: ["scim"],
                },
                samlp: {
                    enabled_features: ["provisioning", "logout"],
                    provisioning_methods: ["scim"],
                },
                waad: {
                    enabled_features: ["provisioning"],
                    provisioning_methods: ["scim"],
                },
            },
            domain_aliases_config: {
                domain_verification: "none",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .get("/config/identity-providers")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.configuration.identityProviders.get();
        }).rejects.toThrow(MyOrganization.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .get("/config/identity-providers")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.configuration.identityProviders.get();
        }).rejects.toThrow(MyOrganization.ForbiddenError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .get("/config/identity-providers")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.configuration.identityProviders.get();
        }).rejects.toThrow(MyOrganization.NotFoundError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };
        server
            .mockEndpoint()
            .get("/config/identity-providers")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.configuration.identityProviders.get();
        }).rejects.toThrow(MyOrganization.TooManyRequestsError);
    });
});
