// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../../../src/api/index";
import { MyOrganizationClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("InvitationsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            next: "next",
            invitations: [
                {
                    id: "uinv_12345678abcdefgh",
                    organization_id: "org_12345678abcdefgh",
                    inviter: { name: "Allison the Admin" },
                    invitee: { email: "user@example.com" },
                    identity_provider_id: "con_2CZPv6IY0gWzDaQJ",
                    created_at: "2025-04-11T20:11:45Z",
                    expires_at: "2025-04-11T20:11:45Z",
                    roles: ["rol_BKW1BKIfBKd0BaI0"],
                    invitation_url:
                        "https://example.auth0.com/login?invitation=uinv_12345678abcdefgh&organization=org_12345678abcdefgh",
                    ticket_id: "1asdfasd23usjdef",
                },
            ],
        };

        server
            .mockEndpoint({ once: false })
            .get("/member-invitations")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.organization.invitations.list({
            fields: "fields",
            include_fields: true,
            from: "from",
            take: 1,
            sort: "sort",
        });

        expect(expected.invitations).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.invitations).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/member-invitations")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.list();
        }).rejects.toThrow(MyOrganization.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/member-invitations")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.list();
        }).rejects.toThrow(MyOrganization.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/member-invitations")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.list();
        }).rejects.toThrow(MyOrganization.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/member-invitations")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.list();
        }).rejects.toThrow(MyOrganization.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/member-invitations")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.list();
        }).rejects.toThrow(MyOrganization.TooManyRequestsError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            invitees: [{ email: "user@example.com", roles: ["rol_0000000000000001"] }],
            inviter: { name: "Allison the Admin" },
            identity_provider_id: "con_2CZPv6IY0gWzDaQJ",
            ttl_sec: 3600,
        };
        const rawResponseBody = [
            {
                id: "uinv_12345678abcdefgh",
                organization_id: "org_12345678abcdefgh",
                inviter: { name: "Allison the Admin" },
                invitee: { email: "user@example.com" },
                identity_provider_id: "con_2CZPv6IY0gWzDaQJ",
                created_at: "2025-04-11T20:11:45Z",
                expires_at: "2025-04-11T20:11:45Z",
                roles: ["rol_BKW1BKIfBKd0BaI0"],
                invitation_url:
                    "https://example.auth0.com/login?invitation=uinv_12345678abcdefgh&organization=org_12345678abcdefgh",
                ticket_id: "1asdfasd23usjdef",
            },
        ];

        server
            .mockEndpoint()
            .post("/member-invitations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organization.invitations.create({
            invitees: [
                {
                    email: "user@example.com",
                    roles: ["rol_0000000000000001"],
                },
            ],
            inviter: {
                name: "Allison the Admin",
            },
            identity_provider_id: "con_2CZPv6IY0gWzDaQJ",
            ttl_sec: 3600,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { invitees: [{ email: "x" }, { email: "x" }] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/member-invitations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.create({
                invitees: [
                    {
                        email: "x",
                    },
                    {
                        email: "x",
                    },
                ],
            });
        }).rejects.toThrow(MyOrganization.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { invitees: [{ email: "x" }, { email: "x" }] };
        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .post("/member-invitations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.create({
                invitees: [
                    {
                        email: "x",
                    },
                    {
                        email: "x",
                    },
                ],
            });
        }).rejects.toThrow(MyOrganization.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { invitees: [{ email: "x" }, { email: "x" }] };
        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .post("/member-invitations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.create({
                invitees: [
                    {
                        email: "x",
                    },
                    {
                        email: "x",
                    },
                ],
            });
        }).rejects.toThrow(MyOrganization.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { invitees: [{ email: "x" }, { email: "x" }] };
        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .post("/member-invitations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.create({
                invitees: [
                    {
                        email: "x",
                    },
                    {
                        email: "x",
                    },
                ],
            });
        }).rejects.toThrow(MyOrganization.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { invitees: [{ email: "x" }, { email: "x" }] };
        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .post("/member-invitations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.create({
                invitees: [
                    {
                        email: "x",
                    },
                    {
                        email: "x",
                    },
                ],
            });
        }).rejects.toThrow(MyOrganization.TooManyRequestsError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "uinv_12345678abcdefgh",
            organization_id: "org_12345678abcdefgh",
            inviter: { name: "Allison the Admin" },
            invitee: { email: "user@example.com" },
            identity_provider_id: "con_2CZPv6IY0gWzDaQJ",
            created_at: "2025-04-11T20:11:45Z",
            expires_at: "2025-04-11T20:11:45Z",
            roles: ["rol_BKW1BKIfBKd0BaI0"],
            invitation_url:
                "https://example.auth0.com/login?invitation=uinv_12345678abcdefgh&organization=org_12345678abcdefgh",
            ticket_id: "1asdfasd23usjdef",
        };

        server
            .mockEndpoint()
            .get("/member-invitations/invitation_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organization.invitations.get("invitation_id", {
            fields: "fields",
            include_fields: true,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/member-invitations/invitation_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.get("invitation_id");
        }).rejects.toThrow(MyOrganization.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/member-invitations/invitation_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.get("invitation_id");
        }).rejects.toThrow(MyOrganization.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/member-invitations/invitation_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.get("invitation_id");
        }).rejects.toThrow(MyOrganization.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/member-invitations/invitation_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.get("invitation_id");
        }).rejects.toThrow(MyOrganization.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .get("/member-invitations/invitation_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.get("invitation_id");
        }).rejects.toThrow(MyOrganization.TooManyRequestsError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/member-invitations/invitation_id").respondWith().statusCode(200).build();

        const response = await client.organization.invitations.delete("invitation_id");
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/member-invitations/invitation_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.delete("invitation_id");
        }).rejects.toThrow(MyOrganization.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .delete("/member-invitations/invitation_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.delete("invitation_id");
        }).rejects.toThrow(MyOrganization.UnauthorizedError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .delete("/member-invitations/invitation_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.delete("invitation_id");
        }).rejects.toThrow(MyOrganization.ForbiddenError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .delete("/member-invitations/invitation_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.delete("invitation_id");
        }).rejects.toThrow(MyOrganization.NotFoundError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server
            .mockEndpoint()
            .delete("/member-invitations/invitation_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organization.invitations.delete("invitation_id");
        }).rejects.toThrow(MyOrganization.TooManyRequestsError);
    });
});
