// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../../../src/api/index";
import { MyOrganizationClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("UserStoresClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            user_stores: [
                {
                    id: "con_abc123",
                    name: "acme-scim",
                    display_name: "Acme SCIM",
                    access_level: "full",
                    member_access_level: "full",
                    is_enabled: true,
                },
            ],
        };

        server.mockEndpoint().get("/user-stores").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.organization.userStores.list({
            member_access_level: ["none"],
            is_enabled: true,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/user-stores").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organization.userStores.list();
        }).rejects.toThrow(MyOrganization.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server.mockEndpoint().get("/user-stores").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organization.userStores.list();
        }).rejects.toThrow(MyOrganization.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server.mockEndpoint().get("/user-stores").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organization.userStores.list();
        }).rejects.toThrow(MyOrganization.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server.mockEndpoint().get("/user-stores").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organization.userStores.list();
        }).rejects.toThrow(MyOrganization.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new MyOrganizationClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { type: "type", status: 1, title: "title", detail: "detail" };

        server.mockEndpoint().get("/user-stores").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organization.userStores.list();
        }).rejects.toThrow(MyOrganization.TooManyRequestsError);
    });
});
