// This file was auto-generated by Fern from our API Definition.

import * as MyOrganization from "../index.js";

/**
 * @example
 *     {
 *         domain: "acme.com"
 *     }
 */
export interface CreateOrganizationDomainRequestContent {
    domain: MyOrganization.OrgDomainName;
}

/**
 * @example
 *     {
 *         domain: "my-domain.com"
 *     }
 */
export interface CreateIdpDomainRequestContent {
    domain: MyOrganization.OrgDomainName;
}

/**
 * @example
 *     {
 *         token_lifetime: 86400
 *     }
 */
export interface CreateIdpProvisioningScimTokenRequestContent {
    /** Lifetime of the token in seconds. Do not set for non-expiring tokens. */
    token_lifetime?: number;
}
