// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { OrganizationDetails } from "./api/resources/organizationDetails/client/Client.js";
import { Organization } from "./api/resources/organization/client/Client.js";

export declare namespace MyOrganizationClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class MyOrganizationClient {
    protected readonly _options: MyOrganizationClient.Options;
    protected _organizationDetails: OrganizationDetails | undefined;
    protected _organization: Organization | undefined;

    constructor(_options: MyOrganizationClient.Options) {
        this._options = _options;
    }

    public get organizationDetails(): OrganizationDetails {
        return (this._organizationDetails ??= new OrganizationDetails(this._options));
    }

    public get organization(): Organization {
        return (this._organization ??= new Organization(this._options));
    }
}
