// This file was auto-generated by Fern from our API Definition.

export const MyOrganizationEnvironment = {
    Default: "https://%7BTENANT%7D.auth0.com/my-org/v1",
} as const;

export type MyOrganizationEnvironment = typeof MyOrganizationEnvironment.Default;
