name: SCA

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    snyk-cli:
        uses: auth0/devsecops-tooling/.github/workflows/sca-scan.yml@main
        secrets: inherit
